### ISSUE TITLE
TypeError: Cannot call method 'getCookieStringSync' of undefined

### ISSUE THREAD

**Issue by larrybolt** [coolaj86/jarson#1]
Using exactly what you described in the README I'm getting next error:
`TypeError: Cannot call method 'getCookieStringSync' of undefined`

Am I doing something wrong that should be obvious?

**Comment by coolaj86** [comment]
Most likely it's because both request and the cookie module updated to have this functionality built in just recently, but I'm pretty sure they require a file name to save to rather than returning a string... Check the issues in those repos and see if you can use their new APIs directly.

—

**Comment by larrybolt** [comment]
Yup, I guess that's the reason. Looking at [tough-cookie-filestore](https://github.com/mitsuru/tough-cookie-filestore), and how the default [MemoryCookieStore](https://github.com/goinstant/tough-cookie/blob/master/lib/memstore.js) is implemented it seems the only way would be to write a "tough-cookie-json" library that simply adds methods to read/load from a String.
